/* ============================================================
   ShopNova — data.js  (Product Database & Mock Data)
   ============================================================ */

const SHOPNOVA_DATA = {

  /* ── Categories ──────────────────────────────────────── */
  categories: [
    { id: 'electronics',  name: 'Electronics',      icon: '💻', color: '#6C63FF', count: 1420 },
    { id: 'fashion',      name: 'Fashion',           icon: '👗', color: '#EC4899', count: 3250 },
    { id: 'home',         name: 'Home & Living',     icon: '🛋️', color: '#F59E0B', count: 890  },
    { id: 'sports',       name: 'Sports & Fitness',  icon: '⚽', color: '#43E97B', count: 640  },
    { id: 'beauty',       name: 'Beauty & Care',     icon: '💄', color: '#F472B6', count: 1100 },
    { id: 'books',        name: 'Books',             icon: '📚', color: '#60A5FA', count: 5200 },
    { id: 'toys',         name: 'Toys & Games',      icon: '🎮', color: '#A78BFA', count: 760  },
    { id: 'automotive',   name: 'Automotive',        icon: '🚗', color: '#34D399', count: 420  },
    { id: 'grocery',      name: 'Grocery',           icon: '🛒', color: '#FBBF24', count: 980  },
    { id: 'jewelry',      name: 'Jewelry',           icon: '💍', color: '#FCD34D', count: 310  },
  ],

  /* ── Products ────────────────────────────────────────── */
  products: [
    {
      id: 1,
      name: 'Sony WH-1000XM5 Wireless Headphones',
      category: 'electronics',
      subcategory: 'Audio',
      brand: 'Sony',
      price: 29990,
      originalPrice: 34990,
      discount: 14,
      rating: 4.8,
      reviewCount: 12420,
      stock: 45,
      sold: 8920,
      image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1524678606370-a47ad25cb82a?w=600&h=600&fit=crop',
      ],
      badge: 'bestseller',
      tags: ['wireless', 'noise-cancelling', 'premium'],
      description: 'Industry-leading noise canceling with 30-hour battery life. Crystal clear hands-free calling. Touch sensor controls for instant, intuitive access to all your music, calls, and your preferred voice assistant.',
      specs: {
        'Driver Size': '30mm',
        'Frequency Response': '4Hz–40kHz',
        'Battery Life': '30 hours',
        'Connectivity': 'Bluetooth 5.2',
        'Weight': '250g',
        'Colors': 'Black, Silver, Midnight Blue',
      },
      colors: ['#1A1A1A', '#C0C0C0', '#1B3A6B'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: true,
      isNew: false,
    },
    {
      id: 2,
      name: 'Apple MacBook Air M3 13-inch',
      category: 'electronics',
      subcategory: 'Laptops',
      brand: 'Apple',
      price: 99900,
      originalPrice: 114900,
      discount: 13,
      rating: 4.9,
      reviewCount: 8730,
      stock: 12,
      sold: 15400,
      image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1611186871525-12a56099e39d?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&h=600&fit=crop',
      ],
      badge: 'new',
      tags: ['laptop', 'apple', 'm3-chip', 'ultrabook'],
      description: 'Supercharged by the M3 chip, MacBook Air is a superportable laptop. Up to 18 hours of battery life. 13.6-inch Liquid Retina display. 8-core CPU and 10-core GPU.',
      specs: {
        'Processor': 'Apple M3',
        'RAM': '8GB / 16GB',
        'Storage': '256GB – 2TB SSD',
        'Display': '13.6" Liquid Retina',
        'Battery': 'Up to 18 hours',
        'Weight': '1.24 kg',
      },
      colors: ['#E8D5B7', '#C0C0C0', '#1A1A1A', '#4A9B9B'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: true,
      isNew: true,
    },
    {
      id: 3,
      name: 'Nike Air Max 270 React',
      category: 'fashion',
      subcategory: 'Sneakers',
      brand: 'Nike',
      price: 9995,
      originalPrice: 12995,
      discount: 23,
      rating: 4.6,
      reviewCount: 5640,
      stock: 234,
      sold: 45600,
      image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=600&h=600&fit=crop',
      ],
      badge: 'sale',
      tags: ['running', 'sneakers', 'sports', 'comfortable'],
      description: 'The Nike Air Max 270 React combines two of Nike\'s greatest technologies to create an air unit and React foam that together deliver ultimate comfort all day long.',
      specs: {
        'Upper': 'Mesh & Synthetic',
        'Sole': 'React foam + Air Max',
        'Closure': 'Lace-up',
        'Sizes': 'US 6–14',
        'Width': 'Standard',
      },
      colors: ['#1A1A1A', '#FFFFFF', '#FF6B35', '#4776E6'],
      sizes: ['6', '7', '8', '9', '10', '11', '12'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '6 Months',
      isTrending: true,
      isFeatured: true,
      isNew: false,
    },
    {
      id: 4,
      name: 'Samsung 65" 4K QLED Smart TV',
      category: 'electronics',
      subcategory: 'TVs',
      brand: 'Samsung',
      price: 69990,
      originalPrice: 99990,
      discount: 30,
      rating: 4.7,
      reviewCount: 3280,
      stock: 8,
      sold: 6740,
      image: 'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1593359677879-a4bb92f829e1?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1567690187548-f07b1d7bf5a9?w=600&h=600&fit=crop',
      ],
      badge: 'sale',
      tags: ['4k', 'smart-tv', 'qled', 'samsung', 'large-screen'],
      description: 'Neo QLED 4K Smart TV with AI-Powered 4K Pro Processor. Quantum Matrix Technology for precise picture control. Real Depth Enhancer for a 3D-like viewing experience.',
      specs: {
        'Display': '65" Neo QLED',
        'Resolution': '4K (3840x2160)',
        'HDR': 'HDR10+',
        'Refresh Rate': '120Hz',
        'Smart TV': 'Tizen OS',
      },
      colors: ['#1A1A1A'],
      freeShipping: true,
      deliveryDays: 5,
      warranty: '2 Years',
      isTrending: false,
      isFeatured: true,
      isNew: false,
    },
    {
      id: 5,
      name: 'Dyson V15 Detect Absolute Vacuum',
      category: 'home',
      subcategory: 'Appliances',
      brand: 'Dyson',
      price: 49900,
      originalPrice: 59900,
      discount: 17,
      rating: 4.7,
      reviewCount: 2140,
      stock: 31,
      sold: 3200,
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop',
      ],
      badge: 'new',
      tags: ['vacuum', 'cordless', 'dyson', 'home-appliance'],
      description: 'The Dyson V15 Detect scientifically proves a deep clean. Laser Detect dust technology reveals invisible dust. Intelligent power adapts automatically to the floor type.',
      specs: {
        'Suction': '230 AW',
        'Run Time': '60 minutes',
        'Filtration': 'Whole-machine HEPA',
        'Weight': '3.1 kg',
        'Bin Volume': '0.77L',
      },
      colors: ['#FFD700', '#C0C0C0'],
      freeShipping: true,
      deliveryDays: 4,
      warranty: '2 Years',
      isTrending: true,
      isFeatured: true,
      isNew: true,
    },
    {
      id: 6,
      name: 'Levi\'s 511 Slim Fit Jeans',
      category: 'fashion',
      subcategory: 'Jeans',
      brand: "Levi's",
      price: 2499,
      originalPrice: 3299,
      discount: 24,
      rating: 4.5,
      reviewCount: 18920,
      stock: 876,
      sold: 124000,
      image: 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1542272604-787c3835535d?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1604176354204-9268737828e4?w=600&h=600&fit=crop',
      ],
      badge: 'bestseller',
      tags: ['jeans', 'denim', 'casual', 'slim-fit'],
      description: 'The iconic Levi\'s 511 Slim Fit jeans. A slim fit from seat to ankle with a slight taper at the ankle. Made from stretch denim for all-day comfort.',
      specs: {
        'Fit': 'Slim',
        'Rise': 'Mid-rise',
        'Material': '98% Cotton, 2% Elastane',
        'Available Waist': '28–38',
        'Inseam': '30/32/34',
      },
      colors: ['#1A2744', '#696969', '#1A1A1A', '#5C3A1E'],
      sizes: ['28x30', '30x32', '32x32', '34x32', '36x32'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: 'N/A',
      isTrending: false,
      isFeatured: false,
      isNew: false,
    },
    {
      id: 7,
      name: 'Instant Pot Duo 7-in-1 Electric Pressure Cooker',
      category: 'home',
      subcategory: 'Kitchen',
      brand: 'Instant Pot',
      price: 5999,
      originalPrice: 8999,
      discount: 33,
      rating: 4.8,
      reviewCount: 32100,
      stock: 540,
      sold: 89000,
      image: 'https://images.unsplash.com/photo-1585515320310-259814833e62?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1585515320310-259814833e62?w=600&h=600&fit=crop',
      ],
      badge: 'bestseller',
      tags: ['kitchen', 'pressure-cooker', 'cooking', 'appliance'],
      description: '7-in-1 multi-use appliance: pressure cooker, slow cooker, rice cooker, steamer, sauté pan, yogurt maker, and warmer.',
      specs: {
        'Capacity': '6 Quart',
        'Programs': '13 one-touch',
        'Material': 'Stainless Steel',
        'Wattage': '1000W',
        'Safety': '10+ safety features',
      },
      colors: ['#C0C0C0'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: false,
      isFeatured: false,
      isNew: false,
    },
    {
      id: 8,
      name: 'Apple iPhone 15 Pro Max',
      category: 'electronics',
      subcategory: 'Smartphones',
      brand: 'Apple',
      price: 134900,
      originalPrice: 159900,
      discount: 16,
      rating: 4.9,
      reviewCount: 24780,
      stock: 56,
      sold: 48200,
      image: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=600&h=600&fit=crop',
        'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=600&h=600&fit=crop',
      ],
      badge: 'trending',
      tags: ['smartphone', 'iphone', '5g', 'pro'],
      description: 'Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever.',
      specs: {
        'Chip': 'Apple A17 Pro',
        'Display': '6.7" Super Retina XDR',
        'Camera': '48MP main + 12MP ultra-wide + 12MP telephoto',
        'Battery': 'Up to 29 hours video',
        'Storage': '256GB – 1TB',
        'OS': 'iOS 17',
      },
      colors: ['#3D3D3D', '#F5F0E8', '#E8E8E8', '#4A5D3D'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: true,
      isNew: true,
    },
    {
      id: 9,
      name: 'Organic Matcha Green Tea Powder',
      category: 'grocery',
      subcategory: 'Beverages',
      brand: 'Jade Leaf',
      price: 1499,
      originalPrice: 2199,
      discount: 32,
      rating: 4.7,
      reviewCount: 8910,
      stock: 1200,
      sold: 34000,
      image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1556679343-c7306c1976bc?w=600&h=600&fit=crop',
      ],
      badge: 'new',
      tags: ['organic', 'matcha', 'tea', 'health'],
      description: 'USDA certified organic matcha green tea powder. Ceremonial grade, single origin from Uji, Japan. Rich, smooth flavor with natural sweetness.',
      specs: {
        'Grade': 'Ceremonial',
        'Origin': 'Uji, Japan',
        'Net Weight': '100g',
        'Certification': 'USDA Organic',
        'Caffeine': '68mg per serving',
      },
      colors: [],
      freeShipping: false,
      deliveryDays: 4,
      warranty: 'N/A',
      isTrending: false,
      isFeatured: false,
      isNew: true,
    },
    {
      id: 10,
      name: 'Fitbit Charge 6 Fitness Tracker',
      category: 'sports',
      subcategory: 'Wearables',
      brand: 'Fitbit',
      price: 12999,
      originalPrice: 14999,
      discount: 13,
      rating: 4.5,
      reviewCount: 6720,
      stock: 189,
      sold: 22400,
      image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=600&h=600&fit=crop',
      ],
      badge: null,
      tags: ['fitness', 'tracker', 'wearable', 'health'],
      description: 'Advanced fitness tracker with built-in GPS, heart rate monitoring, sleep tracking, and 40+ exercise modes.',
      specs: {
        'Display': '1.04" AMOLED',
        'Battery': '7 days',
        'Water Resistance': '50m',
        'GPS': 'Built-in',
        'Heart Rate': 'Continuous 24/7',
        'Compatibility': 'iOS & Android',
      },
      colors: ['#1A1A1A', '#4776E6', '#EC4899'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '1 Year',
      isTrending: false,
      isFeatured: false,
      isNew: false,
    },
    {
      id: 11,
      name: 'Vitamin C + E Facial Serum',
      category: 'beauty',
      subcategory: 'Skincare',
      brand: 'TruSkin',
      price: 899,
      originalPrice: 1299,
      discount: 31,
      rating: 4.6,
      reviewCount: 45320,
      stock: 3400,
      sold: 320000,
      image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=600&h=600&fit=crop',
      ],
      badge: 'bestseller',
      tags: ['serum', 'vitamin-c', 'skincare', 'anti-aging'],
      description: 'Brighten skin, reduce dark spots, and boost collagen with this potent vitamin C serum. Vegan & cruelty-free.',
      specs: {
        'Key Ingredients': 'Vitamin C, Vitamin E, Hyaluronic Acid',
        'Skin Type': 'All skin types',
        'Volume': '1 fl oz (30ml)',
        'Cruelty Free': 'Yes',
        'Vegan': 'Yes',
      },
      colors: [],
      freeShipping: true,
      deliveryDays: 3,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: false,
      isNew: false,
    },
    {
      id: 12,
      name: 'LEGO Technic Ferrari Daytona SP3',
      category: 'toys',
      subcategory: 'Building Sets',
      brand: 'LEGO',
      price: 29999,
      originalPrice: 34999,
      discount: 14,
      rating: 4.9,
      reviewCount: 3280,
      stock: 67,
      sold: 12400,
      image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&h=600&fit=crop',
      ],
      badge: 'trending',
      tags: ['lego', 'technic', 'ferrari', 'collector'],
      description: 'Build the legendary Ferrari Daytona SP3 with 3778 pieces. Features authentic details, working steering, and a realistic V12 engine with moving pistons.',
      specs: {
        'Pieces': '3778',
        'Dimensions': '13" x 6" x 4"',
        'Age': '18+',
        'Scale': '1:8',
        'Moving Parts': 'Pistons, steering, doors',
      },
      colors: ['#D40000'],
      freeShipping: true,
      deliveryDays: 4,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: true,
      isNew: false,
    },
    {
      id: 13,
      name: 'Atomic Habits by James Clear',
      category: 'books',
      subcategory: 'Self-Help',
      brand: 'Avery',
      price: 499,
      originalPrice: 799,
      discount: 38,
      rating: 4.9,
      reviewCount: 89430,
      stock: 5000,
      sold: 1200000,
      image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&h=600&fit=crop',
      ],
      badge: 'bestseller',
      tags: ['book', 'self-help', 'habits', 'productivity'],
      description: 'No.1 bestselling guide to building good habits. James Clear reveals practical strategies for forming good habits, breaking bad ones.',
      specs: {
        'Format': 'Hardcover / Paperback',
        'Pages': '320',
        'Language': 'English',
        'Publisher': 'Avery',
        'ISBN': '9780735211292',
      },
      colors: [],
      freeShipping: true,
      deliveryDays: 2,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: false,
      isNew: false,
    },
    {
      id: 14,
      name: 'Weber Genesis E-325s Gas Grill',
      category: 'home',
      subcategory: 'Outdoor',
      brand: 'Weber',
      price: 69900,
      originalPrice: 84900,
      discount: 18,
      rating: 4.7,
      reviewCount: 4120,
      stock: 23,
      sold: 8900,
      image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=600&fit=crop',
      ],
      badge: null,
      tags: ['grill', 'bbq', 'outdoor', 'cooking'],
      description: 'Three stainless steel burners. Enclosed cart design for a built-in look. WEBER CRAFTED frame rail for added cooking accessories.',
      specs: {
        'Burners': '3 stainless steel',
        'BTU': '39,000',
        'Cooking Area': '669 sq in',
        'Fuel': 'Propane / Natural Gas',
        'Ignition': 'Push-to-Start',
      },
      colors: ['#1A1A1A'],
      freeShipping: false,
      deliveryDays: 7,
      warranty: '10 Years',
      isTrending: false,
      isFeatured: false,
      isNew: false,
    },
    {
      id: 15,
      name: 'Yoga Mat Premium Non-Slip 6mm',
      category: 'sports',
      subcategory: 'Yoga',
      brand: 'Manduka',
      price: 1999,
      originalPrice: 2999,
      discount: 33,
      rating: 4.8,
      reviewCount: 12780,
      stock: 432,
      sold: 68000,
      image: 'https://images.unsplash.com/photo-1601925228017-99f4d0c2b57b?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1601925228017-99f4d0c2b57b?w=600&h=600&fit=crop',
      ],
      badge: null,
      tags: ['yoga', 'mat', 'fitness', 'exercise'],
      description: 'Professional-grade yoga mat with superior cushioning and grip. Eco-friendly materials, sweat-proof surface, and lifetime guarantee.',
      specs: {
        'Thickness': '6mm',
        'Material': 'Natural rubber + microfiber',
        'Dimensions': '71" x 24"',
        'Weight': '2.2 kg',
        'Grip': 'Non-slip top surface',
      },
      colors: ['#1A1A1A', '#4776E6', '#EC4899', '#43E97B'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: 'Lifetime',
      isTrending: false,
      isFeatured: false,
      isNew: false,
    },
    {
      id: 16,
      name: 'Dell XPS 15 9530 Laptop',
      category: 'electronics',
      subcategory: 'Laptops',
      brand: 'Dell',
      price: 144900,
      originalPrice: 179900,
      discount: 19,
      rating: 4.6,
      reviewCount: 3840,
      stock: 28,
      sold: 12300,
      image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=400&h=400&fit=crop',
      images: [
        'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&h=600&fit=crop',
      ],
      badge: 'sale',
      tags: ['laptop', 'dell', 'xps', 'workstation'],
      description: 'Ultra-thin, premium laptop with 15.6" OLED display, Intel Core i7 processor, and NVIDIA RTX graphics. Perfect for creators and professionals.',
      specs: {
        'Processor': 'Intel Core i7-13700H',
        'RAM': '16GB DDR5',
        'Storage': '512GB NVMe SSD',
        'Display': '15.6" OLED 3.5K',
        'GPU': 'NVIDIA RTX 4060',
        'Battery': 'Up to 13 hours',
      },
      colors: ['#C0C0C0'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '2 Years',
      isTrending: false,
      isFeatured: false,
      isNew: false,
    },
    {
      id: 17,
      name: 'Sony PlayStation 5 Slim Console',
      category: 'electronics',
      subcategory: 'Gaming',
      brand: 'Sony',
      price: 44990,
      originalPrice: 54990,
      discount: 18,
      rating: 4.9,
      reviewCount: 15400,
      stock: 120,
      sold: 84000,
      image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['gaming', 'playstation', 'ps5', 'console'],
      description: 'Experience lightning-fast loading with an ultra-high speed SSD, deeper immersion with support for haptic feedback, adaptive triggers, and 3D Audio.',
      specs: { 'Storage': '1TB Custom SSD', 'Resolution': 'Up to 4K 120Hz', 'HDR': 'Yes', 'Audio': 'Tempest 3D AudioTech' },
      colors: ['#FFFFFF', '#1A1A1A'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: true,
      isNew: true
    },
    {
      id: 18,
      name: 'Canon EOS R6 Mark II Mirrorless Camera',
      category: 'electronics',
      subcategory: 'Cameras',
      brand: 'Canon',
      price: 215990,
      originalPrice: 243990,
      discount: 11,
      rating: 4.8,
      reviewCount: 1920,
      stock: 14,
      sold: 5200,
      image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=600&h=600&fit=crop'],
      badge: 'new',
      tags: ['camera', 'canon', 'mirrorless', 'photography', '4k-video'],
      description: 'Full-frame mirrorless camera delivering up to 40 fps continuous shooting, 24.2 MP CMOS sensor, and uncropped 4K 60p video.',
      specs: { 'Sensor': '24.2MP Full-Frame CMOS', 'Video': '4K 60p 10-bit', 'Autofocus': 'Dual Pixel CMOS AF II', 'Stabilization': 'In-Body 8-Stops' },
      colors: ['#1A1A1A'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '2 Years',
      isTrending: true,
      isFeatured: true,
      isNew: true
    },
    {
      id: 19,
      name: 'Apple iPad Air M2 11-inch',
      category: 'electronics',
      subcategory: 'Tablets',
      brand: 'Apple',
      price: 54900,
      originalPrice: 59900,
      discount: 8,
      rating: 4.9,
      reviewCount: 6320,
      stock: 45,
      sold: 32100,
      image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=600&h=600&fit=crop'],
      badge: 'trending',
      tags: ['ipad', 'apple', 'tablet', 'm2-chip'],
      description: 'Fresh design with Liquid Retina display, supercharged by the Apple M2 chip. Supports Apple Pencil Pro and Magic Keyboard.',
      specs: { 'Display': '11" Liquid Retina', 'Chip': 'Apple M2', 'Storage': '128GB - 1TB', 'Battery': 'Up to 10 hours' },
      colors: ['#C0C0C0', '#E8D5B7', '#4A9B9B', '#A78BFA'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: false,
      isNew: true
    },
    {
      id: 20,
      name: 'Adidas Originals Trefoil Fleece Hoodie',
      category: 'fashion',
      subcategory: 'Hoodies',
      brand: 'Adidas',
      price: 3499,
      originalPrice: 4499,
      discount: 22,
      rating: 4.7,
      reviewCount: 8900,
      stock: 340,
      sold: 42000,
      image: 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['hoodie', 'adidas', 'streetwear', 'casual', 'fleece'],
      description: 'Cozy heavyweight French terry fleece hoodie featuring the iconic Adidas Trefoil logo on the chest. Regular fit with drawcord hood.',
      specs: { 'Material': '100% Cotton French Terry', 'Fit': 'Regular', 'Care': 'Machine wash cold' },
      colors: ['#1A1A1A', '#696969', '#4776E6', '#EC4899'],
      sizes: ['S', 'M', 'L', 'XL', 'XXL'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: false,
      isNew: false
    },
    {
      id: 21,
      name: 'Ray-Ban Classic Wayfarer Sunglasses',
      category: 'fashion',
      subcategory: 'Eyewear',
      brand: 'Ray-Ban',
      price: 9490,
      originalPrice: 12490,
      discount: 24,
      rating: 4.8,
      reviewCount: 14200,
      stock: 150,
      sold: 95000,
      image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['sunglasses', 'ray-ban', 'eyewear', 'style'],
      description: 'The iconic Ray-Ban Original Wayfarer Classic is the most recognizable style in sunglasses history since 1952. 100% UV protection.',
      specs: { 'Frame Material': 'Acetate', 'Lens Width': '50mm', 'UV Protection': '100% UV400' },
      colors: ['#1A1A1A', '#5C3A1E'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '2 Years',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 22,
      name: 'Michael Kors Jet Set Leather Tote Handbag',
      category: 'fashion',
      subcategory: 'Handbags',
      brand: 'Michael Kors',
      price: 14995,
      originalPrice: 21995,
      discount: 32,
      rating: 4.6,
      reviewCount: 4520,
      stock: 88,
      sold: 21000,
      image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&h=600&fit=crop'],
      badge: 'sale',
      tags: ['handbag', 'tote', 'leather', 'luxury', 'michael-kors'],
      description: 'Saffiano leather tote with top zip closure, gold-tone hardware, and multiple interior slip pockets. Spaciously sized for daily essentials.',
      specs: { 'Material': '100% Saffiano Leather', 'Dimensions': '15"W x 10"H x 4.5"D', 'Hardware': 'Gold-tone' },
      colors: ['#1A1A1A', '#5C3A1E', '#E8D5B7', '#EC4899'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '1 Year',
      isTrending: false,
      isFeatured: true,
      isNew: false
    },
    {
      id: 23,
      name: 'Fossil Gen 6 Touchscreen Smartwatch',
      category: 'fashion',
      subcategory: 'Watches',
      brand: 'Fossil',
      price: 11995,
      originalPrice: 18995,
      discount: 37,
      rating: 4.4,
      reviewCount: 3120,
      stock: 65,
      sold: 14000,
      image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop'],
      badge: 'sale',
      tags: ['watch', 'smartwatch', 'fossil', 'wearable'],
      description: 'Powered with Wear OS by Google. Fast charging (80% in 30 mins), Snapdragon Wear 4100+ platform, heart rate and SpO2 sensors.',
      specs: { 'Processor': 'Qualcomm Snapdragon Wear 4100+', 'OS': 'Wear OS by Google', 'Case Size': '44mm' },
      colors: ['#1A1A1A', '#C0C0C0', '#5C3A1E'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '2 Years',
      isTrending: false,
      isFeatured: false,
      isNew: false
    },
    {
      id: 24,
      name: 'Zara Linen Blend Slim Fit Casual Shirt',
      category: 'fashion',
      subcategory: 'Shirts',
      brand: 'Zara',
      price: 2490,
      originalPrice: 3290,
      discount: 24,
      rating: 4.5,
      reviewCount: 2890,
      stock: 410,
      sold: 18500,
      image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=600&h=600&fit=crop'],
      badge: null,
      tags: ['shirt', 'linen', 'zara', 'summer', 'casual'],
      description: 'Lightweight breathable linen blend shirt with mandarin collar, buttoned cuffs, and slim fit silhouette. Essential summer attire.',
      specs: { 'Material': '55% Linen, 45% Cotton', 'Fit': 'Slim Fit', 'Collar': 'Mandarin' },
      colors: ['#FFFFFF', '#E8D5B7', '#4776E6'],
      sizes: ['S', 'M', 'L', 'XL'],
      freeShipping: false,
      deliveryDays: 4,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: false,
      isNew: true
    },
    {
      id: 25,
      name: 'Philips Hue Smart LED Starter Kit',
      category: 'home',
      subcategory: 'Lighting',
      brand: 'Philips',
      price: 9999,
      originalPrice: 12999,
      discount: 23,
      rating: 4.7,
      reviewCount: 7800,
      stock: 95,
      sold: 38000,
      image: 'https://images.unsplash.com/photo-1550985616-10810253b84d?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1550985616-10810253b84d?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['smart-home', 'lighting', 'philips-hue', 'led'],
      description: 'Set the mood with 16 million colors. Includes 4 A19 E26 smart bulbs and the Hue Bridge hub for full home automation.',
      specs: { 'Bulb Type': 'A19 E26', 'Colors': '16 Million', 'Hub': 'Hue Bridge Included', 'Voice Control': 'Alexa, Google, Apple Home' },
      colors: ['#FFFFFF'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '3 Years',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 26,
      name: 'Nespresso Vertuo Next Coffee & Espresso Maker',
      category: 'home',
      subcategory: 'Kitchen',
      brand: 'Nespresso',
      price: 12990,
      originalPrice: 16990,
      discount: 24,
      rating: 4.6,
      reviewCount: 11400,
      stock: 110,
      sold: 67000,
      image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=600&h=600&fit=crop'],
      badge: 'sale',
      tags: ['coffee', 'espresso', 'nespresso', 'kitchen'],
      description: 'Brews a wide range of coffee sizes at the touch of a button: 5oz, 8oz, 12oz, plus single and double espresso shots using Centrifusion technology.',
      specs: { 'Technology': 'Centrifusion Extraction', 'Water Tank': '37 oz', 'Heat-up Time': '25 seconds' },
      colors: ['#1A1A1A', '#C0C0C0', '#D40000'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '1 Year',
      isTrending: false,
      isFeatured: true,
      isNew: false
    },
    {
      id: 27,
      name: 'Herman Miller Aeron Ergonomic Chair',
      category: 'home',
      subcategory: 'Furniture',
      brand: 'Herman Miller',
      price: 99990,
      originalPrice: 125000,
      discount: 20,
      rating: 4.9,
      reviewCount: 5600,
      stock: 18,
      sold: 24000,
      image: 'https://images.unsplash.com/photo-1580481072645-022f9a6d8310?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1580481072645-022f9a6d8310?w=600&h=600&fit=crop'],
      badge: 'premium',
      tags: ['chair', 'office', 'ergonomic', 'herman-miller'],
      description: 'The gold standard in ergonomic office seating. Pellicle 8Z suspension material provides eight zones of varying tension for optimal support.',
      specs: { 'Frame': 'Graphite', 'Mechanism': 'Tilt Limiter + Forward Tilt', 'Armrests': 'Fully Adjustable' },
      colors: ['#1A1A1A', '#696969'],
      freeShipping: true,
      deliveryDays: 5,
      warranty: '12 Years',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 28,
      name: 'Bowflex SelectTech 552 Dumbbells (Pair)',
      category: 'sports',
      subcategory: 'Gym',
      brand: 'Bowflex',
      price: 34999,
      originalPrice: 42999,
      discount: 19,
      rating: 4.8,
      reviewCount: 9820,
      stock: 42,
      sold: 45000,
      image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['dumbbells', 'fitness', 'weights', 'bowflex', 'home-gym'],
      description: 'Adjusts from 5 to 52.5 lbs in 2.5 lb increments. Replaces 15 sets of weights in one compact system with easy selection dial.',
      specs: { 'Weight Range': '5 to 52.5 lbs each', 'Increments': '2.5 lbs', 'Dimensions': '16.9"L x 8.3"W x 9"H' },
      colors: ['#1A1A1A', '#D40000'],
      freeShipping: true,
      deliveryDays: 4,
      warranty: '2 Years',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 29,
      name: 'Garmin Forerunner 965 GPS Watch',
      category: 'sports',
      subcategory: 'Wearables',
      brand: 'Garmin',
      price: 49999,
      originalPrice: 54999,
      discount: 9,
      rating: 4.9,
      reviewCount: 3410,
      stock: 38,
      sold: 16200,
      image: 'https://images.unsplash.com/photo-1510017803434-a899398421b3?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1510017803434-a899398421b3?w=600&h=600&fit=crop'],
      badge: 'new',
      tags: ['garmin', 'running', 'gps', 'watch', 'triathlon'],
      description: 'Premium GPS running and triathlon smartwatch with vibrant AMOLED touchscreen display, titanium bezel, and built-in full-color mapping.',
      specs: { 'Display': '1.4" AMOLED', 'Battery': 'Up to 23 days in smartwatch mode', 'GPS': 'Multi-band GNSS' },
      colors: ['#1A1A1A', '#FF6B35', '#C0C0C0'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: false,
      isNew: true
    },
    {
      id: 30,
      name: 'Spalding TF-1000 Legacy Basketball',
      category: 'sports',
      subcategory: 'Equipment',
      brand: 'Spalding',
      price: 3499,
      originalPrice: 4499,
      discount: 22,
      rating: 4.7,
      reviewCount: 4120,
      stock: 190,
      sold: 28000,
      image: 'https://images.unsplash.com/photo-1519861531473-9200262188bf?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1519861531473-9200262188bf?w=600&h=600&fit=crop'],
      badge: null,
      tags: ['basketball', 'spalding', 'sports', 'game-ball'],
      description: 'Exclusive ZK microfiber composite leather cover for soft feel and moisture management. NFHS approved for high school play.',
      specs: { 'Size': 'Official Size 7 (29.5")', 'Material': 'ZK Microfiber Leather', 'Use': 'Indoor' },
      colors: ['#FF6B35'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '1 Year',
      isTrending: false,
      isFeatured: false,
      isNew: false
    },
    {
      id: 31,
      name: 'Olaplex No. 3 Hair Perfector Treatment',
      category: 'beauty',
      subcategory: 'Haircare',
      brand: 'Olaplex',
      price: 2450,
      originalPrice: 2950,
      discount: 17,
      rating: 4.8,
      reviewCount: 38900,
      stock: 850,
      sold: 290000,
      image: 'https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1527799820374-dcf8d9d4a388?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['olaplex', 'haircare', 'repair', 'treatment', 'beauty'],
      description: 'At-home bond-building treatment that reduces breakage and visibly strengthens hair, improving its look and feel.',
      specs: { 'Volume': '100ml / 3.3 fl oz', 'Hair Type': 'All Hair Types', 'PH Level': '3.5-5.0' },
      colors: [],
      freeShipping: true,
      deliveryDays: 2,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 32,
      name: 'Dior Sauvage Eau de Parfum 100ml',
      category: 'beauty',
      subcategory: 'Fragrance',
      brand: 'Dior',
      price: 11500,
      originalPrice: 13500,
      discount: 15,
      rating: 4.9,
      reviewCount: 21500,
      stock: 120,
      sold: 140000,
      image: 'https://images.unsplash.com/photo-1594035910387-fea47794261f?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1594035910387-fea47794261f?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['perfume', 'cologne', 'dior', 'fragrance', 'luxury'],
      description: 'A radically fresh composition, raw and noble all at once. Radiant top notes of Calabrian Bergamot release a powerful woody trail of Papua New Guinean Vanilla.',
      specs: { 'Volume': '100ml / 3.4 oz', 'Type': 'Eau de Parfum', 'Fragrance Family': 'Woody & Citrus' },
      colors: [],
      freeShipping: true,
      deliveryDays: 3,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 33,
      name: 'Laneige Lip Sleeping Mask (Berry)',
      category: 'beauty',
      subcategory: 'Skincare',
      brand: 'Laneige',
      price: 1450,
      originalPrice: 1750,
      discount: 17,
      rating: 4.8,
      reviewCount: 52100,
      stock: 1200,
      sold: 380000,
      image: 'https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['lip-mask', 'laneige', 'skincare', 'k-beauty'],
      description: 'An overnight lip mask that delivers intense moisture and antioxidants while you sleep with Berry Mix Complex and Vitamin C.',
      specs: { 'Volume': '20g / 0.70 oz', 'Flavor': 'Berry', 'Key Ingredients': 'Berry Mix Complex, Vitamin C, Hyaluronic Acid' },
      colors: [],
      freeShipping: true,
      deliveryDays: 2,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: false,
      isNew: false
    },
    {
      id: 34,
      name: 'Dyson Airwrap Multi-Styler Complete Long',
      category: 'beauty',
      subcategory: 'Haircare',
      brand: 'Dyson',
      price: 45900,
      originalPrice: 49900,
      discount: 8,
      rating: 4.7,
      reviewCount: 8910,
      stock: 25,
      sold: 41000,
      image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=600&fit=crop'],
      badge: 'new',
      tags: ['dyson', 'airwrap', 'hairstyler', 'beauty'],
      description: 'Curl, shape, smooth, and hide flyaways with no extreme heat. Uses Coanda airflow technology to style hair while drying.',
      specs: { 'Airflow': '13.5 l/s', 'Heat Settings': '3 precise heat settings', 'Wattage': '1300W' },
      colors: ['#EC4899', '#C0C0C0'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '2 Years',
      isTrending: true,
      isFeatured: true,
      isNew: true
    },
    {
      id: 35,
      name: 'The Psychology of Money by Morgan Housel',
      category: 'books',
      subcategory: 'Finance',
      brand: 'Harriman House',
      price: 399,
      originalPrice: 499,
      discount: 20,
      rating: 4.9,
      reviewCount: 42100,
      stock: 3200,
      sold: 680000,
      image: 'https://images.unsplash.com/photo-1592496001020-d31bd816657f?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1592496001020-d31bd816657f?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['book', 'finance', 'investing', 'psychology'],
      description: 'Timeless lessons on wealth, greed, and happiness doing well with money isn’t necessarily about what you know. It’s about how you behave.',
      specs: { 'Pages': '256', 'Format': 'Hardcover', 'Language': 'English' },
      colors: [],
      freeShipping: true,
      deliveryDays: 2,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 36,
      name: 'Clean Code: Handbook of Software Craftsmanship',
      category: 'books',
      subcategory: 'Technology',
      brand: 'Prentice Hall',
      price: 1999,
      originalPrice: 2499,
      discount: 20,
      rating: 4.7,
      reviewCount: 12400,
      stock: 890,
      sold: 150000,
      image: 'https://images.unsplash.com/photo-1532012197267-da84d127e765?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1532012197267-da84d127e765?w=600&h=600&fit=crop'],
      badge: null,
      tags: ['book', 'programming', 'software', 'tech', 'coding'],
      description: 'Even bad code can function. But if code isn’t clean, it can bring a development organization to its knees. Master the principles of clean code.',
      specs: { 'Author': 'Robert C. Martin', 'Pages': '464', 'Language': 'English' },
      colors: [],
      freeShipping: true,
      deliveryDays: 3,
      warranty: 'N/A',
      isTrending: false,
      isFeatured: false,
      isNew: false
    },
    {
      id: 37,
      name: 'Dune Deluxe Hardcover Edition by Frank Herbert',
      category: 'books',
      subcategory: 'Sci-Fi',
      brand: 'Penguin',
      price: 1499,
      originalPrice: 1999,
      discount: 25,
      rating: 4.9,
      reviewCount: 19800,
      stock: 1100,
      sold: 240000,
      image: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=600&h=600&fit=crop'],
      badge: 'trending',
      tags: ['book', 'sci-fi', 'dune', 'fiction', 'novel'],
      description: 'Frank Herbert’s classic masterpiece — a triumph of the imagination and one of the bestselling science fiction novels of all time.',
      specs: { 'Pages': '688', 'Format': 'Deluxe Hardcover', 'Language': 'English' },
      colors: [],
      freeShipping: true,
      deliveryDays: 2,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: false,
      isNew: false
    },
    {
      id: 38,
      name: 'Catan Strategy Board Game',
      category: 'toys',
      subcategory: 'Board Games',
      brand: 'Catan',
      price: 2999,
      originalPrice: 3999,
      discount: 25,
      rating: 4.8,
      reviewCount: 28400,
      stock: 430,
      sold: 210000,
      image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['board-game', 'catan', 'toys', 'strategy'],
      description: 'Picture yourself in the era of discovery: after a long voyage of great hardship, your ships have finally reached the coast of an uncharted island.',
      specs: { 'Players': '3-4 Players', 'Play Time': '60 Minutes', 'Age': '10+' },
      colors: [],
      freeShipping: true,
      deliveryDays: 3,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 39,
      name: 'DJI Mini 3 Ultra-Lightweight Drone',
      category: 'toys',
      subcategory: 'RC Toys',
      brand: 'DJI',
      price: 42999,
      originalPrice: 49999,
      discount: 14,
      rating: 4.7,
      reviewCount: 4120,
      stock: 54,
      sold: 22000,
      image: 'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1527977966376-1c8408f9f108?w=600&h=600&fit=crop'],
      badge: 'new',
      tags: ['drone', 'dji', 'camera-drone', '4k-video', 'rc'],
      description: 'Under 249g lightweight camera drone with 4K HDR video, 38-min max flight time, True Vertical Shooting, and intelligent features.',
      specs: { 'Weight': '< 249g', 'Video': '4K HDR 30fps', 'Flight Time': 'Up to 38 mins', 'Transmission Range': '10 km' },
      colors: ['#C0C0C0'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: true,
      isNew: true
    },
    {
      id: 40,
      name: 'Nintendo Switch OLED Model - White',
      category: 'toys',
      subcategory: 'Video Games',
      brand: 'Nintendo',
      price: 28999,
      originalPrice: 31999,
      discount: 9,
      rating: 4.9,
      reviewCount: 31200,
      stock: 85,
      sold: 190000,
      image: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['nintendo', 'switch', 'gaming', 'console', 'oled'],
      description: 'Features a vibrant 7-inch OLED screen, wide adjustable stand, wired LAN port, 64 GB of internal storage, and enhanced audio.',
      specs: { 'Screen': '7" OLED', 'Storage': '64GB Internal', 'Modes': 'TV, Tabletop, Handheld' },
      colors: ['#FFFFFF', '#1A1A1A'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 41,
      name: 'REDTIGER 4K Front & Rear Dash Cam',
      category: 'automotive',
      subcategory: 'Electronics',
      brand: 'REDTIGER',
      price: 9999,
      originalPrice: 14999,
      discount: 33,
      rating: 4.6,
      reviewCount: 8920,
      stock: 210,
      sold: 48000,
      image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&h=600&fit=crop'],
      badge: 'sale',
      tags: ['dashcam', 'car-camera', 'automotive', '4k', 'gps'],
      description: 'Ultra HD 4K front camera and 1080P rear camera. Built-in WiFi and GPS, night vision, 24-hour parking monitor, and 170° wide angle.',
      specs: { 'Resolution': '4K Front + 1080P Rear', 'Screen': '3.16" IPS', 'Features': 'WiFi, GPS, Night Vision' },
      colors: ['#1A1A1A'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 42,
      name: 'NOCO Boost Plus GB40 1000A Jump Starter',
      category: 'automotive',
      subcategory: 'Tools',
      brand: 'NOCO',
      price: 7999,
      originalPrice: 9999,
      discount: 20,
      rating: 4.8,
      reviewCount: 45100,
      stock: 670,
      sold: 320000,
      image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['jump-starter', 'noco', 'car-battery', 'automotive', 'emergency'],
      description: 'Compact 1000-Amp lithium battery jump starter pack for up to 20 jump starts on a single charge. Spark-proof technology & reverse polarity protection.',
      specs: { 'Peak Current': '1000 Amps', 'Engine Rating': 'Up to 6.0L Gas, 3.0L Diesel', 'LED Flashlight': '100 Lumens' },
      colors: ['#1A1A1A', '#FF6B35'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: false,
      isNew: false
    },
    {
      id: 43,
      name: 'Chemical Guys 16-Piece Master Car Wash Kit',
      category: 'automotive',
      subcategory: 'Care',
      brand: 'Chemical Guys',
      price: 7499,
      originalPrice: 9999,
      discount: 25,
      rating: 4.7,
      reviewCount: 12400,
      stock: 310,
      sold: 84000,
      image: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=600&h=600&fit=crop'],
      badge: 'sale',
      tags: ['car-wash', 'car-detailing', 'chemical-guys', 'automotive'],
      description: 'Complete 16-piece detailing bucket kit with Foam Blaster wash gun, Citrus Wash & Gloss soap, Diablo Wheel Gel, and plush microfiber towels.',
      specs: { 'Pieces': '16 items', 'Includes': 'Foam Gun, Bucket, Soaps, Microfiber Towels' },
      colors: [],
      freeShipping: true,
      deliveryDays: 3,
      warranty: 'N/A',
      isTrending: false,
      isFeatured: true,
      isNew: false
    },
    {
      id: 44,
      name: 'Bosch ICON 26A Premium Wiper Blade',
      category: 'automotive',
      subcategory: 'Accessories',
      brand: 'Bosch',
      price: 1499,
      originalPrice: 1999,
      discount: 25,
      rating: 4.6,
      reviewCount: 18900,
      stock: 1400,
      sold: 160000,
      image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&h=600&fit=crop'],
      badge: null,
      tags: ['wiper-blades', 'bosch', 'automotive', 'car-parts'],
      description: 'Exclusive fx dual rubber resists heat and ozone deterioration and proven to last up to 40% longer than other premium wiper blades.',
      specs: { 'Size': '26 Inch', 'Design': 'Beam blade', 'Lifespan': 'Up to 40% longer' },
      colors: ['#1A1A1A'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: false,
      isFeatured: false,
      isNew: false
    },
    {
      id: 45,
      name: 'Blue Bottle Coffee Whole Bean Single Origin 12oz',
      category: 'grocery',
      subcategory: 'Coffee',
      brand: 'Blue Bottle',
      price: 1299,
      originalPrice: 1699,
      discount: 24,
      rating: 4.8,
      reviewCount: 6710,
      stock: 850,
      sold: 54000,
      image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&h=600&fit=crop'],
      badge: 'new',
      tags: ['coffee', 'whole-bean', 'blue-bottle', 'gourmet', 'grocery'],
      description: 'Freshly roasted single-origin specialty coffee beans with notes of dark chocolate, toasted marshmallow, and stone fruit.',
      specs: { 'Net Weight': '12 oz / 340g', 'Roast Level': 'Medium', 'Origin': 'Single Origin Blend' },
      colors: [],
      freeShipping: false,
      deliveryDays: 3,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: true,
      isNew: true
    },
    {
      id: 46,
      name: 'Kirkland Signature Organic EVOO 2 Liters',
      category: 'grocery',
      subcategory: 'Organic',
      brand: 'Kirkland',
      price: 1999,
      originalPrice: 2499,
      discount: 20,
      rating: 4.9,
      reviewCount: 28900,
      stock: 2100,
      sold: 290000,
      image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['olive-oil', 'organic', 'kirkland', 'cooking', 'grocery'],
      description: 'USDA certified 100% Italian organic extra virgin olive oil. First cold-pressed for superior flavor and high antioxidant content.',
      specs: { 'Volume': '2 Liters / 67.6 fl oz', 'Pressing': 'First Cold Pressed', 'Certification': 'USDA Organic' },
      colors: [],
      freeShipping: true,
      deliveryDays: 3,
      warranty: 'N/A',
      isTrending: false,
      isFeatured: false,
      isNew: false
    },
    {
      id: 47,
      name: 'KIND Protein Bars Dark Chocolate Nut 12-Pack',
      category: 'grocery',
      subcategory: 'Snacks',
      brand: 'KIND',
      price: 1499,
      originalPrice: 1899,
      discount: 21,
      rating: 4.7,
      reviewCount: 14200,
      stock: 1800,
      sold: 110000,
      image: 'https://images.unsplash.com/photo-1622484210800-88517572bf92?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1622484210800-88517572bf92?w=600&h=600&fit=crop'],
      badge: null,
      tags: ['protein-bar', 'kind', 'snacks', 'healthy', 'grocery'],
      description: '12g of plant-based protein per bar. Made with heart-healthy whole nuts and dark chocolate. Gluten-free with low glycemic index.',
      specs: { 'Pack Size': '12 Bars (1.76 oz each)', 'Protein': '12g per bar', 'Gluten Free': 'Yes' },
      colors: [],
      freeShipping: true,
      deliveryDays: 2,
      warranty: 'N/A',
      isTrending: false,
      isFeatured: false,
      isNew: false
    },
    {
      id: 48,
      name: 'Pandora Moments Snake Chain Charm Bracelet',
      category: 'jewelry',
      subcategory: 'Bracelets',
      brand: 'Pandora',
      price: 4990,
      originalPrice: 6490,
      discount: 23,
      rating: 4.8,
      reviewCount: 19400,
      stock: 310,
      sold: 125000,
      image: 'https://images.unsplash.com/photo-1611591475777-233ca70be3ee?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1611591475777-233ca70be3ee?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['jewelry', 'bracelet', 'pandora', 'silver', 'charms'],
      description: 'Hand-finished in 925 sterling silver. Iconic snake chain design with barrel clasp to hold your favorite Pandora charms.',
      specs: { 'Material': '925 Sterling Silver', 'Clasp': 'Barrel Clasp', 'Sizes': '17cm - 21cm' },
      colors: ['#C0C0C0'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 49,
      name: 'Swarovski Angelic Crystal Tennis Bracelet',
      category: 'jewelry',
      subcategory: 'Bracelets',
      brand: 'Swarovski',
      price: 9990,
      originalPrice: 12990,
      discount: 23,
      rating: 4.7,
      reviewCount: 8120,
      stock: 145,
      sold: 58000,
      image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=600&fit=crop'],
      badge: 'sale',
      tags: ['jewelry', 'bracelet', 'swarovski', 'crystal', 'luxury'],
      description: 'Classic rhodium-plated tennis bracelet featuring a row of clear round crystals in circular bezel settings.',
      specs: { 'Plating': 'Rhodium Plated', 'Length': '17 cm / 6.6 inches', 'Stone': 'Swarovski Crystals' },
      colors: ['#C0C0C0'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '2 Years',
      isTrending: false,
      isFeatured: true,
      isNew: false
    },
    {
      id: 50,
      name: '14K Yellow Gold Solitaire Diamond Pendant',
      category: 'jewelry',
      subcategory: 'Necklaces',
      brand: 'Brilliant Earth',
      price: 34999,
      originalPrice: 49999,
      discount: 30,
      rating: 4.9,
      reviewCount: 3210,
      stock: 42,
      sold: 19000,
      image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&h=600&fit=crop'],
      badge: 'premium',
      tags: ['jewelry', 'necklace', 'diamond', 'gold', 'luxury'],
      description: 'Timeless 0.25 carat round brilliant lab-created diamond set in 14K yellow gold 4-prong basket setting with 18-inch chain.',
      specs: { 'Carat Weight': '0.25 ct', 'Metal': '14K Yellow Gold', 'Chain Length': '18 inches' },
      colors: ['#FFD700'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: 'Lifetime',
      isTrending: true,
      isFeatured: true,
      isNew: true
    },
    {
      id: 51,
      name: 'Dell XPS 15 OLED Touchscreen Laptop',
      category: 'electronics',
      subcategory: 'Laptops',
      brand: 'Dell',
      price: 29990,
      originalPrice: 34990,
      discount: 14,
      rating: 4.8,
      reviewCount: 4210,
      stock: 18,
      sold: 6300,
      image: 'https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=600&h=600&fit=crop'],
      badge: 'trending',
      tags: ['laptop', 'dell', 'xps', 'oled', '4k'],
      description: '15.6-inch 3.5K OLED Touch Display with 13th Gen Intel Core i7, 16GB RAM, 1TB SSD, and NVIDIA RTX 4060 graphics.',
      specs: { 'Processor': 'Intel Core i7-13700H', 'Display': '15.6" 3.5K OLED Touch', 'RAM': '16GB DDR5', 'Storage': '1TB NVMe SSD', 'GPU': 'NVIDIA RTX 4060 8GB' },
      colors: ['#C0C0C0', '#1A1A1A'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: true,
      isNew: true
    },
    {
      id: 52,
      name: 'Bose QuietComfort Ultra Wireless Earbuds',
      category: 'electronics',
      subcategory: 'Audio',
      brand: 'Bose',
      price: 99900,
      originalPrice: 114900,
      discount: 13,
      rating: 4.7,
      reviewCount: 5120,
      stock: 64,
      sold: 14200,
      image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=600&h=600&fit=crop'],
      badge: 'new',
      tags: ['earbuds', 'bose', 'wireless', 'noise-cancelling'],
      description: 'Breakthrough spatialized audio for immersive listening. World-class noise cancellation and CustomTune technology for personalized sound.',
      specs: { 'Battery Life': '6 hours (24 with case)', 'Connectivity': 'Bluetooth 5.3', 'Water Resistance': 'IPX4' },
      colors: ['#1A1A1A', '#F5F5F0'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: false,
      isNew: true
    },
    {
      id: 53,
      name: 'Adidas Ultraboost 1.0 Running Shoes',
      category: 'fashion',
      subcategory: 'Sneakers',
      brand: 'Adidas',
      price: 9995,
      originalPrice: 12995,
      discount: 23,
      rating: 4.8,
      reviewCount: 16800,
      stock: 140,
      sold: 89000,
      image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['running', 'adidas', 'ultraboost', 'sneakers'],
      description: 'Iconic running shoes with full-length BOOST midsole for ultimate energy return and PRIMEKNIT upper that hugs your foot.',
      specs: { 'Upper': 'Adidas PRIMEKNIT', 'Midsole': 'Full-length BOOST', 'Outsole': 'Continental Rubber' },
      colors: ['#1A1A1A', '#FFFFFF', '#4A9B9B'],
      sizes: ['7', '8', '9', '10', '11', '12'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '6 Months',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 54,
      name: 'Ray-Ban Classic Aviator Sunglasses G-15',
      category: 'fashion',
      subcategory: 'Accessories',
      brand: 'Ray-Ban',
      price: 69990,
      originalPrice: 99990,
      discount: 30,
      rating: 4.8,
      reviewCount: 12400,
      stock: 95,
      sold: 67000,
      image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['sunglasses', 'ray-ban', 'aviator', 'fashion'],
      description: 'The iconic pilot shape sunglasses designed in 1937. Arista gold metal frame with G-15 green crystal glass lenses providing 100% UV protection.',
      specs: { 'Frame Material': 'Metal', 'Lens Technology': 'G-15 Crystal Glass', 'UV Protection': '100% UV400' },
      colors: ['#FFD700', '#C0C0C0', '#1A1A1A'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '2 Years',
      isTrending: false,
      isFeatured: true,
      isNew: false
    },
    {
      id: 55,
      name: 'Nespresso VertuoPlus Coffee & Espresso Machine',
      category: 'home',
      subcategory: 'Kitchen',
      brand: 'Nespresso',
      price: 49900,
      originalPrice: 59900,
      discount: 17,
      rating: 4.7,
      reviewCount: 9450,
      stock: 42,
      sold: 38000,
      image: 'https://images.unsplash.com/photo-1517668808822-9eaa02ae2d32?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1517668808822-9eaa02ae2d32?w=600&h=600&fit=crop'],
      badge: 'sale',
      tags: ['coffee', 'nespresso', 'espresso', 'kitchen', 'home'],
      description: 'Single-serve coffee maker utilizing Centrifusion technology to brew smooth, crema-rich coffee and authentic espresso at the touch of a button.',
      specs: { 'Water Tank': '60 oz', 'Heat Up Time': '20 seconds', 'Cup Sizes': '5 sizes (1.35oz to 14oz)' },
      colors: ['#1A1A1A', '#C0C0C0', '#8B0000'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: false,
      isNew: false
    },
    {
      id: 56,
      name: 'Philips Hue Smart LED Color Starter Kit',
      category: 'home',
      subcategory: 'Smart Home',
      brand: 'Philips',
      price: 2499,
      originalPrice: 3299,
      discount: 24,
      rating: 4.8,
      reviewCount: 7890,
      stock: 50,
      sold: 29000,
      image: 'https://images.unsplash.com/photo-1550985616-10810253b84d?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1550985616-10810253b84d?w=600&h=600&fit=crop'],
      badge: 'trending',
      tags: ['smart-home', 'lighting', 'philips-hue', 'alexa', 'home'],
      description: 'Includes 4 A19 smart color bulbs and Hue Bridge. 16 million colors, automated schedules, and seamless voice control with Alexa, Google Assistant & Apple HomeKit.',
      specs: { 'Bulb Wattage': '75W Equivalent', 'Protocol': 'Zigbee + Bluetooth', 'Ecosystems': 'Alexa, Google, HomeKit' },
      colors: [],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '2 Years',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 57,
      name: 'Bowflex SelectTech 552 Adjustable Dumbbells',
      category: 'sports',
      subcategory: 'Strength',
      brand: 'Bowflex',
      price: 5999,
      originalPrice: 8999,
      discount: 33,
      rating: 4.8,
      reviewCount: 24500,
      stock: 25,
      sold: 62000,
      image: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['fitness', 'dumbbells', 'bowflex', 'gym', 'workout'],
      description: 'Adjusts from 5 to 52.5 lbs in 2.5 lb increments. Replaces 15 sets of weights in one compact system. Turn of a dial automatically changes resistance.',
      specs: { 'Weight Range': '5 to 52.5 lbs per dumbbell', 'Increments': '15 settings', 'Dimensions': '16.9" L x 8.3" W x 9" H' },
      colors: ['#1A1A1A'],
      freeShipping: true,
      deliveryDays: 4,
      warranty: '2 Years',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 58,
      name: 'Garmin Forerunner 265 Running Smartwatch',
      category: 'sports',
      subcategory: 'Wearables',
      brand: 'Garmin',
      price: 134900,
      originalPrice: 159900,
      discount: 16,
      rating: 4.9,
      reviewCount: 3890,
      stock: 33,
      sold: 11200,
      image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop'],
      badge: 'new',
      tags: ['garmin', 'running', 'gps', 'smartwatch', 'sports'],
      description: 'Vibrant AMOLED touchscreen display. Training readiness score, multi-band GPS tracking, morning report, and up to 13 days of battery life in smartwatch mode.',
      specs: { 'Display': '1.3" AMOLED Touchscreen', 'Battery': '13 days (smartwatch), 20 hrs (GPS)', 'Water Rating': '5 ATM' },
      colors: ['#1A1A1A', '#4776E6', '#EC4899'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: false,
      isNew: true
    },
    {
      id: 59,
      name: 'Olaplex No. 3 Hair Perfector Repairing Treatment',
      category: 'beauty',
      subcategory: 'Haircare',
      brand: 'Olaplex',
      price: 1499,
      originalPrice: 2199,
      discount: 32,
      rating: 4.8,
      reviewCount: 38400,
      stock: 450,
      sold: 210000,
      image: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['haircare', 'olaplex', 'beauty', 'treatment'],
      description: 'At-home bond building treatment that reduces breakage and visibly strengthens hair, improving its look and feel. Suitable for all hair types.',
      specs: { 'Volume': '100 ml / 3.3 fl oz', 'Key Ingredient': 'Bis-Aminopropyl Diglycol Dimaleate', 'Paraben Free': 'Yes' },
      colors: [],
      freeShipping: true,
      deliveryDays: 3,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 60,
      name: 'Dyson Airwrap Multi-Styler Complete Long',
      category: 'beauty',
      subcategory: 'Styling Tools',
      brand: 'Dyson',
      price: 12999,
      originalPrice: 14999,
      discount: 13,
      rating: 4.7,
      reviewCount: 8920,
      stock: 14,
      sold: 45000,
      image: 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=600&h=600&fit=crop'],
      badge: 'premium',
      tags: ['dyson', 'airwrap', 'hairstyling', 'beauty', 'luxury'],
      description: 'Curl, shape, smooth, and hide flyaways with no extreme heat. Utilizes the Coanda airflow effect to wrap and style hair automatically.',
      specs: { 'Power': '1300W', 'Airflow': '13.5 l/s', 'Heat Settings': '3 heat, 3 speed, Cold Shot' },
      colors: ['#FFD700', '#EC4899', '#1A1A1A'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '2 Years',
      isTrending: true,
      isFeatured: true,
      isNew: true
    },
    {
      id: 61,
      name: 'Thinking, Fast and Slow by Daniel Kahneman',
      category: 'books',
      subcategory: 'Psychology',
      brand: 'FSG',
      price: 899,
      originalPrice: 1299,
      discount: 31,
      rating: 4.8,
      reviewCount: 42100,
      stock: 1200,
      sold: 680000,
      image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['book', 'psychology', 'kahneman', 'non-fiction'],
      description: 'Nobel laureate Daniel Kahneman takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think: System 1 (fast) and System 2 (slow).',
      specs: { 'Format': 'Paperback / Hardcover', 'Pages': '512', 'Publisher': 'Farrar, Straus and Giroux' },
      colors: [],
      freeShipping: true,
      deliveryDays: 2,
      warranty: 'N/A',
      isTrending: false,
      isFeatured: true,
      isNew: false
    },
    {
      id: 62,
      name: 'The Psychology of Money by Morgan Housel',
      category: 'books',
      subcategory: 'Finance',
      brand: 'Harriman House',
      price: 29999,
      originalPrice: 34999,
      discount: 14,
      rating: 4.9,
      reviewCount: 56300,
      stock: 1800,
      sold: 890000,
      image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['book', 'finance', 'investing', 'housel', 'money'],
      description: 'Timeless lessons on wealth, greed, and happiness. 19 short stories exploring the strange ways people think about money and teaching how to make better sense of financial decisions.',
      specs: { 'Format': 'Paperback', 'Pages': '256', 'Language': 'English' },
      colors: [],
      freeShipping: true,
      deliveryDays: 2,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 63,
      name: 'Nintendo Switch OLED Model - White Set',
      category: 'toys',
      subcategory: 'Gaming Consoles',
      brand: 'Nintendo',
      price: 499,
      originalPrice: 799,
      discount: 38,
      rating: 4.9,
      reviewCount: 31200,
      stock: 38,
      sold: 145000,
      image: 'https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1578303512597-81e6cc155b3e?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['nintendo', 'switch', 'oled', 'gaming', 'toys'],
      description: 'Featuring a vibrant 7-inch OLED screen, wide adjustable stand, wired LAN port dock, 64 GB internal storage, and enhanced audio.',
      specs: { 'Screen': '7.0" OLED (1280x720)', 'Storage': '64 GB Internal', 'Battery': '4.5 to 9 hours' },
      colors: ['#FFFFFF', '#1A1A1A', '#FF6B35'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 64,
      name: 'LEGO Star Wars Millennium Falcon Collector Series',
      category: 'toys',
      subcategory: 'Building Sets',
      brand: 'LEGO',
      price: 69900,
      originalPrice: 84900,
      discount: 18,
      rating: 4.9,
      reviewCount: 4120,
      stock: 12,
      sold: 18500,
      image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&h=600&fit=crop'],
      badge: 'premium',
      tags: ['lego', 'star-wars', 'millennium-falcon', 'collector'],
      description: 'The ultimate Star Wars LEGO model. 7,541 pieces featuring intricate detailing, cockpit, sensor dishes, and 7 minifigures.',
      specs: { 'Pieces': '7,541', 'Age': '18+', 'Dimensions': '33" L x 23" W x 8" H' },
      colors: [],
      freeShipping: true,
      deliveryDays: 4,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 65,
      name: 'NOCO Boost Plus GB40 1000A Car Jump Starter',
      category: 'automotive',
      subcategory: 'Car Care',
      brand: 'NOCO',
      price: 1999,
      originalPrice: 2999,
      discount: 33,
      rating: 4.7,
      reviewCount: 84500,
      stock: 120,
      sold: 340000,
      image: 'https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1486006920555-c77dce18193b?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['car', 'battery', 'jump-starter', 'noco', 'automotive'],
      description: 'Portable lithium car battery jump starter pack for 12V batteries. Up to 20 jump starts on a single charge. Spark-proof technology and reverse polarity protection.',
      specs: { 'Peak Current': '1000 Amps', 'Gas Engine Rating': '6.0 Liters', 'LED Flashlight': '100 Lumens' },
      colors: ['#1A1A1A'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: false,
      isNew: false
    },
    {
      id: 66,
      name: 'Nextbase 622GW 4K Dash Cam Image Stabilization',
      category: 'automotive',
      subcategory: 'Electronics',
      brand: 'Nextbase',
      price: 144900,
      originalPrice: 179900,
      discount: 19,
      rating: 4.8,
      reviewCount: 4120,
      stock: 28,
      sold: 14200,
      image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&h=600&fit=crop'],
      badge: 'new',
      tags: ['dash-cam', '4k', 'nextbase', 'car-camera', 'automotive'],
      description: 'Ultra HD 4K recording at 30fps with digital image stabilization, Emergency SOS response, what3words location tracking, and Alexa Built-In.',
      specs: { 'Resolution': '4K @ 30fps / 1440p @ 60fps', 'Viewing Angle': '140°', 'Screen': '3" HD IPS Touchscreen' },
      colors: ['#1A1A1A'],
      freeShipping: true,
      deliveryDays: 3,
      warranty: '1 Year',
      isTrending: false,
      isFeatured: true,
      isNew: true
    },
    {
      id: 67,
      name: 'Nespresso Vertuo Line Coffee Pods Variety Pack 40ct',
      category: 'grocery',
      subcategory: 'Beverages',
      brand: 'Nespresso',
      price: 44990,
      originalPrice: 54990,
      discount: 18,
      rating: 4.9,
      reviewCount: 28400,
      stock: 850,
      sold: 420000,
      image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['coffee', 'nespresso', 'pods', 'grocery', 'beverages'],
      description: 'Includes 40 aluminum capsules across 4 dark and medium roast blends: Stormio, Odacio, Melozio, and Solelio (7.77 fl oz brews).',
      specs: { 'Count': '40 Capsules', 'Brews': '7.77 fl oz Coffee', 'Recyclable': 'Aluminum Pods' },
      colors: [],
      freeShipping: true,
      deliveryDays: 2,
      warranty: 'N/A',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 68,
      name: 'Nutiva Organic Cold-Pressed Extra Virgin Coconut Oil',
      category: 'grocery',
      subcategory: 'Pantry',
      brand: 'Nutiva',
      price: 215990,
      originalPrice: 243990,
      discount: 11,
      rating: 4.8,
      reviewCount: 19800,
      stock: 620,
      sold: 180000,
      image: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1526947425960-945c6e72858f?w=600&h=600&fit=crop'],
      badge: 'sale',
      tags: ['organic', 'coconut-oil', 'nutiva', 'cooking', 'grocery'],
      description: 'USDA Certified Organic, Non-GMO, unrefined cold-pressed extra virgin coconut oil. Perfect for cooking, baking, skin, and hair care.',
      specs: { 'Volume': '54 fl oz / 1.6 Liters', 'Processing': 'Cold-Pressed Unrefined', 'Organic': 'USDA Certified' },
      colors: [],
      freeShipping: true,
      deliveryDays: 3,
      warranty: 'N/A',
      isTrending: false,
      isFeatured: false,
      isNew: false
    },
    {
      id: 69,
      name: 'Tiffany & Co. Loving Heart Pendant Silver Necklace',
      category: 'jewelry',
      subcategory: 'Necklaces',
      brand: 'Tiffany & Co.',
      price: 54900,
      originalPrice: 59900,
      discount: 8,
      rating: 4.9,
      reviewCount: 6890,
      stock: 22,
      sold: 34000,
      image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=600&h=600&fit=crop'],
      badge: 'bestseller',
      tags: ['jewelry', 'tiffany', 'necklace', 'silver', 'luxury'],
      description: 'Designed by Paloma Picasso. Sterling silver open heart pendant on a 16-inch chain. Delivered in signature Tiffany Blue box.',
      specs: { 'Material': '925 Sterling Silver', 'Chain Length': '16 inches', 'Designer': 'Paloma Picasso' },
      colors: ['#C0C0C0'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '1 Year',
      isTrending: true,
      isFeatured: true,
      isNew: false
    },
    {
      id: 70,
      name: 'Seiko Presage Automatic Stainless Steel Watch',
      category: 'jewelry',
      subcategory: 'Watches',
      brand: 'Seiko',
      price: 3499,
      originalPrice: 4499,
      discount: 22,
      rating: 4.8,
      reviewCount: 5120,
      stock: 19,
      sold: 21000,
      image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=400&fit=crop',
      images: ['https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=600&h=600&fit=crop'],
      badge: 'new',
      tags: ['watch', 'seiko', 'presage', 'automatic', 'jewelry'],
      description: 'Japanese automatic movement (Caliber 4R35) with 41-hour power reserve. Sunburst blue dial, stainless steel case, and see-through case back.',
      specs: { 'Movement': 'Automatic 4R35', 'Water Resistance': '50 Meters / 5 Bar', 'Case Diameter': '40.5 mm' },
      colors: ['#C0C0C0', '#1B3A6B'],
      freeShipping: true,
      deliveryDays: 2,
      warranty: '3 Years',
      isTrending: true,
      isFeatured: true,
      isNew: true
    },
  ],

  /* ── Deals of the Day ────────────────────────────────── */
  dealsOfDay: [
    { productId: 3, endsAt: Date.now() + 3600000 * 8, sold: 234, total: 500 },
    { productId: 7, endsAt: Date.now() + 3600000 * 5, sold: 189, total: 300 },
    { productId: 11, endsAt: Date.now() + 3600000 * 12, sold: 1420, total: 2000 },
    { productId: 13, endsAt: Date.now() + 3600000 * 20, sold: 890, total: 1200 },
  ],

  /* ── Reviews ─────────────────────────────────────────── */
  reviews: {
    1: [
      { id: 'r1', user: 'Alex K.', avatar: 'A', rating: 5, date: '2024-02-15', title: 'Best headphones I\'ve ever owned!', text: 'The noise cancellation is absolutely incredible. I wore these on a 10-hour flight and could not hear a thing. Battery life is outstanding too.', verified: true, helpful: 234, unhelpful: 12 },
      { id: 'r2', user: 'Sarah M.', avatar: 'S', rating: 5, date: '2024-01-28', title: 'Worth every penny', text: 'Exceptional sound quality and comfort. After 6 hours of use, my ears don\'t hurt at all. The touch controls are super intuitive.', verified: true, helpful: 156, unhelpful: 8 },
      { id: 'r3', user: 'James T.', avatar: 'J', rating: 4, date: '2024-01-10', title: 'Almost perfect', text: 'Great headphones overall. The ANC is top-notch and sound quality is superb. Only minor complaint is that they\'re a bit tight initially.', verified: false, helpful: 89, unhelpful: 22 },
      { id: 'r1a', user: 'Nina R.', avatar: 'N', rating: 5, date: '2024-03-02', title: 'Travel essential!', text: 'I travel for work every week. These are the only headphones I trust. The Multipoint Bluetooth is a game changer — connected to my laptop and phone simultaneously.', verified: true, helpful: 178, unhelpful: 4 },
      { id: 'r1b', user: 'David W.', avatar: 'D', rating: 3, date: '2024-02-01', title: 'Great sound, mediocre mic', text: 'The listening experience is fantastic. However, during calls the mic picks up too much background noise. Decent for music but not ideal for video calls.', verified: true, helpful: 67, unhelpful: 31 },
    ],
    2: [
      { id: 'r2a', user: 'Priya S.', avatar: 'P', rating: 5, date: '2024-03-05', title: 'Absolute powerhouse', text: 'The M3 chip handles everything I throw at it — 4K video editing, Xcode builds, everything. And the battery genuinely lasts all day.', verified: true, helpful: 521, unhelpful: 14 },
      { id: 'r2b', user: 'Carlos M.', avatar: 'C', rating: 5, date: '2024-02-22', title: 'Perfect ultrabook', text: 'Switched from a Windows laptop. The Liquid Retina display is gorgeous and the keyboard is a dream to type on for hours.', verified: true, helpful: 344, unhelpful: 9 },
      { id: 'r2c', user: 'Yuki T.', avatar: 'Y', rating: 4, date: '2024-02-10', title: 'Impressive but pricey', text: 'Performance is stellar and build quality is top-tier. Docked one star because the base model only comes with 8GB RAM in 2024.', verified: false, helpful: 211, unhelpful: 33 },
    ],
    3: [
      { id: 'r3a', user: 'Marcus J.', avatar: 'M', rating: 5, date: '2024-02-28', title: 'Best running shoes!', text: 'The React foam cushioning is out of this world. My knees don\'t ache anymore after long runs. Sizing is true to size.', verified: true, helpful: 198, unhelpful: 7 },
      { id: 'r3b', user: 'Lily C.', avatar: 'L', rating: 4, date: '2024-02-14', title: 'Great all-rounder', text: 'Stylish, comfortable, and durable. Wore these for a half-marathon and they held up great. The Air Max unit gives noticeable bounce.', verified: true, helpful: 143, unhelpful: 11 },
      { id: 'r3c', user: 'Omar F.', avatar: 'O', rating: 3, date: '2024-01-30', title: 'Nice but runs narrow', text: 'Love the colorway and the cushioning is great. But if you have wide feet, size up by half. Took a week to break in.', verified: true, helpful: 88, unhelpful: 24 },
    ],
    8: [
      { id: 'r4', user: 'Emma L.', avatar: 'E', rating: 5, date: '2024-02-20', title: 'Life-changing camera', text: 'The camera system is absolutely mind-blowing. The ProRes video, the zoom capabilities – nothing else comes close.', verified: true, helpful: 445, unhelpful: 28 },
      { id: 'r5', user: 'Ryan P.', avatar: 'R', rating: 5, date: '2024-02-10', title: 'Best iPhone yet', text: 'The titanium build feels premium and the performance is incredible. Battery life is much improved over my old 13 Pro.', verified: true, helpful: 312, unhelpful: 19 },
      { id: 'r5a', user: 'Aisha B.', avatar: 'A', rating: 4, date: '2024-01-25', title: 'Almost flawless', text: 'A17 Pro chip is insanely fast. Face ID is instant. My one gripe is the USB-C cable included is too short. Otherwise a top-tier phone.', verified: true, helpful: 267, unhelpful: 15 },
    ],
    11: [
      { id: 'r11a', user: 'Grace H.', avatar: 'G', rating: 5, date: '2024-03-01', title: 'Transformed my skin!', text: 'After 4 weeks of daily use, my dark spots are noticeably lighter and my skin has a healthy glow. Will definitely repurchase.', verified: true, helpful: 892, unhelpful: 21 },
      { id: 'r11b', user: 'Fatima A.', avatar: 'F', rating: 5, date: '2024-02-18', title: 'Best serum I\'ve tried', text: 'I\'ve tried drugstore and luxury serums. This affordable gem beats most of them. Lightweight, non-greasy, and absorbs quickly.', verified: true, helpful: 654, unhelpful: 18 },
      { id: 'r11c', user: 'Chloe K.', avatar: 'C', rating: 4, date: '2024-02-05', title: 'Effective but smells strong', text: 'Definitely works — my skin texture has improved dramatically. The vitamin C smell is a bit strong but fades quickly after application.', verified: false, helpful: 321, unhelpful: 44 },
    ],
    13: [
      { id: 'r13a', user: 'Ben A.', avatar: 'B', rating: 5, date: '2024-03-03', title: 'Life-changing book', text: '1% better every day. James Clear\'s framework for building habits is backed by real science and narrated in a totally accessible way. Read it twice already.', verified: true, helpful: 1203, unhelpful: 31 },
      { id: 'r13b', user: 'Mei L.', avatar: 'M', rating: 5, date: '2024-02-20', title: 'Everyone should read this', text: 'The concept of identity-based habits was a revelation for me. I\'ve maintained a daily exercise and reading streak for 3 months since finishing this.', verified: true, helpful: 987, unhelpful: 22 },
      { id: 'r13c', user: 'Tom H.', avatar: 'T', rating: 4, date: '2024-02-08', title: 'Great but some repetition', text: 'Excellent content and very practical. A few chapters feel repetitive. Still, the implementation tips alone are worth the price.', verified: true, helpful: 445, unhelpful: 67 },
    ],
  },

  /* ── Q&A Data ─────────────────────────────────────────── */
  qa: {
    1: [
      { id: 'q1', question: 'Does it work with Android phones or only Apple?', askedBy: 'Mike R.', date: '2024-01-20', answers: [
        { id: 'a1', answer: 'Yes! It works with any Bluetooth device — Android, Apple, Windows, everything. No limitation at all.', answeredBy: 'ShopNova Support', date: '2024-01-21', isOfficial: true, helpful: 45 },
        { id: 'a1b', answer: 'I use it with my Samsung Galaxy S24 daily. Works perfectly.', answeredBy: 'Alex K.', date: '2024-01-22', isOfficial: false, helpful: 23 },
      ]},
      { id: 'q2', question: 'Can I use these for calls at the office?', askedBy: 'Linda T.', date: '2024-02-01', answers: [
        { id: 'a2', answer: 'Yes, the mic quality is good for calls. The ANC helps block office noise. Teams and Zoom work great.', answeredBy: 'Sarah M.', date: '2024-02-02', isOfficial: false, helpful: 31 },
      ]},
    ],
    8: [
      { id: 'q3', question: 'Does this come with MagSafe charger in the box?', askedBy: 'Kevin S.', date: '2024-02-05', answers: [
        { id: 'a3', answer: 'No, only a USB-C cable is included. You\'ll need to purchase MagSafe separately, or it charges fine with any USB-C PD charger.', answeredBy: 'ShopNova Support', date: '2024-02-06', isOfficial: true, helpful: 78 },
      ]},
    ],
  },

  /* ── Banner Slides ───────────────────────────────────── */
  banners: [
    {
      id: 1,
      title: 'The Future of Sound',
      subtitle: 'Sony WH-1000XM5 — Industry-leading noise cancellation',
      cta: 'Shop Now',
      ctaLink: 'product-detail.html?id=1',
      badge: '🎵 Up to 30hrs battery',
      accentColor: '#6C63FF',
      productId: 1,
    },
    {
      id: 2,
      title: 'Powered by M3',
      subtitle: 'MacBook Air — Outrageously thin. Seriously powerful.',
      cta: 'Explore Now',
      ctaLink: 'product-detail.html?id=2',
      badge: '✨ New Arrival',
      accentColor: '#4776E6',
      productId: 2,
    },
    {
      id: 3,
      title: 'Season\'s Biggest Sale',
      subtitle: 'Up to 50% off on thousands of products',
      cta: 'View Deals',
      ctaLink: 'products.html?sale=true',
      badge: '🔥 Limited Time',
      accentColor: '#FF6B35',
      productId: 3,
    },
  ],

  /* ── Users (Demo) ────────────────────────────────────── */
  demoUsers: [
    { id: 'u1', name: 'John Doe', email: 'john@demo.com', password: 'demo1234', avatar: 'J', joinDate: '2023-01-15', tier: 'Gold', orders: 42, totalSpent: 4820.50 },
    { id: 'u2', name: 'Admin User', email: 'admin@shopnova.com', password: 'admin1234', avatar: 'A', joinDate: '2022-06-01', tier: 'Platinum', isAdmin: true, orders: 0, totalSpent: 0 },
  ],

  /* ── Orders (Demo) ───────────────────────────────────── */
  demoOrders: [
    { id: 'SN-2024-001', date: '2024-02-18', status: 'delivered', items: [{ productId: 1, qty: 1, price: 349.99 }, { productId: 13, qty: 2, price: 14.99 }], total: 379.97, shipping: 0, address: '123 Main St, New York, NY 10001' },
    { id: 'SN-2024-002', date: '2024-02-25', status: 'shipped', items: [{ productId: 8, qty: 1, price: 1199.00 }], total: 1199.00, shipping: 0, address: '456 Oak Ave, Los Angeles, CA 90001' },
    { id: 'SN-2024-003', date: '2024-03-01', status: 'processing', items: [{ productId: 3, qty: 1, price: 129.99 }, { productId: 11, qty: 1, price: 19.99 }], total: 149.98, shipping: 0, address: '789 Pine St, Chicago, IL 60601' },
  ],

  /* ── Notifications ───────────────────────────────────── */
  notifications: [
    { id: 'n1', type: 'order', icon: '📦', title: 'Order Delivered', message: 'Your Sony headphones have been delivered!', time: '2 hours ago', read: false },
    { id: 'n2', type: 'deal', icon: '🔥', title: 'Flash Deal Alert', message: 'iPhone 15 Pro — 8% off for 4 more hours!', time: '5 hours ago', read: false },
    { id: 'n3', type: 'review', icon: '⭐', title: 'Review Request', message: 'How did you like your MacBook Air?', time: '1 day ago', read: true },
    { id: 'n4', type: 'promo', icon: '🎁', title: 'You\'ve earned Gold status!', message: 'Enjoy exclusive member discounts and free shipping!', time: '2 days ago', read: true },
  ],
};

// ── Helper functions ──────────────────────────────────────
function getProduct(id) {
  return SHOPNOVA_DATA.products.find(p => p.id === Number(id));
}

function getProductsByCategory(cat) {
  if (!cat || cat === 'all') return SHOPNOVA_DATA.products;
  return SHOPNOVA_DATA.products.filter(p => p.category === cat);
}

function getFeaturedProducts() {
  return SHOPNOVA_DATA.products.filter(p => p.isFeatured);
}

function getTrendingProducts() {
  return SHOPNOVA_DATA.products.filter(p => p.isTrending);
}

function getRelatedProducts(product, limit = 4) {
  return SHOPNOVA_DATA.products
    .filter(p => p.category === product.category && p.id !== product.id)
    .slice(0, limit);
}

function searchProducts(query) {
  const q = query.toLowerCase();
  return SHOPNOVA_DATA.products.filter(p =>
    p.name.toLowerCase().includes(q) ||
    p.brand.toLowerCase().includes(q) ||
    p.tags.some(t => t.includes(q)) ||
    p.category.includes(q)
  );
}

function formatPrice(num) {
  if (typeof I18N !== 'undefined' && I18N.formatPrice) {
    return I18N.formatPrice(num);
  }
  return '₹' + Math.round(Number(num) || 0).toLocaleString('en-IN');
}

function calcDiscount(orig, curr) {
  return Math.round((1 - curr / orig) * 100);
}

function getStockStatus(stock) {
  if (stock === 0) return { label: 'Out of Stock', cls: 'danger' };
  if (stock <= 10) return { label: `Only ${stock} left!`, cls: 'warning' };
  return { label: 'In Stock', cls: 'success' };
}
